/aruco_detection:
  ros__parameters:
    marker_size: 0.10
    aruco_dictionary_id: DICT_ARUCO_ORIGINAL
    image_topic: /zed_four/zed_node/rgb/image_rect_color
    camera_info_topic: /zed_four/zed_node/rgb/camera_info